name: ServiceNow DevOps Pipeline

on: [push] # Se ejecuta cada vez que subes código

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ESTE PASO ES EL QUE SE COMUNICA CON SERVICENOW
      - name: ServiceNow DevOps Change
        uses: ServiceNow/servicenow-devops-change@v3.1.0
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'Build'
          change-request-details: '{"short_description":"Despliegue automático desde GitHub"}'
